config/routes.rb
MyeCommerce::Application.routes.draw do
	

    #common
    match '/admin',   to: 'admin/products#index'  
 
    (StaticPagesController.action_methods - ApplicationController.action_methods).each do |am|
      match "/#{am}" => "static_pages##{am}"
    end

    root to: 'static_pages#home'

    #back-end
    namespace "admin" do
		  resources :products, :categories
	  end

    #front-end Store 

    resources :items, :only => [:create, :destroy]
    resources :carts, only: [:show, :destroy]
    
    resources :products, :only => [:show]
    resources :categories, :only => [:show]

  	devise_for :users
    
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :qty
  belongs_to	:cart
  belongs_to	:product


  def total_price
  	self.product.price * self.qty  	
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def create
  		cart=current_user.my_cart
  		product = Product.find(params[:id])
  		cart.add_item(product)
    	redirect_to cart_path(cart)    	
  end

  def destroy

      item = Item.find(params[:id])
  		cart=item.cart
  		product = item.product
  		cart.remove_item(product)
      cart.save
    	redirect_to cart_path(cart)
  end


end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/_item.html.erb
<% product = item.product %>
<tr>
	<td class="cart-details">					
		<span class="cart-image"><%=image_tag(product.picture, :size => "100x100")  %></span>		
		<h3><%= link_to product.name, product_path(product) %></h3>	 				
	</td>
	<td class="cart-price"><%=number_to_currency(product.sale_price )%></td>
	<td class="cart-price">
		<%=item.qty%>
	</td>
	<td class="total"><%=number_to_currency(item.total_price)%></td>
	<td class="total"><%=link_to "Delete Item", item_path(id: item.id), method: :delete, data: { confirm: 'Are you sure?' }%></td>
</tr>
	