config/routes.rb
MyeCommerce::Application.routes.draw do
	

    #common
    match '/admin',   to: 'admin/products#index'  
 
    (StaticPagesController.action_methods - ApplicationController.action_methods).each do |am|
      match "/#{am}" => "static_pages##{am}"
    end

    root to: 'static_pages#home'

    #back-end
    namespace "admin" do
		  resources :products, :categories
	  end

    #front-end Store 

    resources :items, :only => [:create, :destroy]
    resources :carts, only: [:show, :destroy]
    
    resources :products, :only => [:show]
    resources :categories, :only => [:show]

  	devise_for :users
    
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :on_sale, :price, :qty, :sale_price, :category_id, :picture
  
  belongs_to :category
  has_many 	:items
  has_many	:carts, :through => :items

  if Rails.env.production?
   has_attached_file :picture, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :storage => :s3, :s3_credentials => S3_CREDENTIALS
 else
   has_attached_file :picture, :styles => { :medium => "200x200>", :thumb => "100x100>" }
 end

 

 validates_presence_of :description, :name, :price, :qty
 validates_uniqueness_of :name
 validates_numericality_of :price, :qty, greater_than_or_equal_to: 0


 validates_attachment :picture,
 content_type: { content_type: /^image\/.?(gif|png|jpg|jpeg)$/i },
 size: { in: 1..500.kilobytes }
 
 scope :in_stock, where("qty > ?", 0)

  #searchable do
    #text :name, :description
  #end

  def total_price
    on_sale ? sale_price : price
  end

  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['name LIKE ? OR description LIKE ?', search_condition, search_condition])
  end



end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  before_filter :get_product, :only => [:show, :edit, :update, :destroy]
   load_and_authorize_resource  

  respond_to :html, :json, :js


  def index
    @products = Product.order("name").page(params[:page]).per(10)
    respond_with(@products)
  end

  def show
    
    respond_with(@product)
  end


  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
    
  end

  def create
    
    flash[:success] = "Product was successfully created." if @product.save
    redirect_to(admin_products_path)
  end


  def update
    
    flash[:success] = "Product was successfully updated." if @product.update_attributes(params[:product])
    respond_with(@product)
   end

  def destroy
    @product.destroy
    redirect_to admin_products_path
  end  

  def get_product
    @product = Product.find(params[:id])
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	layout "store_layout"

	respond_to :html, :json, :js
	before_filter :authenticate_user!


	def show
		@product = Product.find(params[:id])
		respond_with(@product)
	end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product])  do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.input :name, :input_html =>{:required => "required"} %>
   <%= f.input :picture, :as => :file, :label => "Picture"%>
   <%= f.input :description, :input_html =>{:required => "required"} %>
   <%= f.input :qty, :input_html =>{:required => "required", :min=>"1"} %>
   <%= f.input :price, :input_html =>{:required => "required", :min=>"1"} %>
   <%= f.input :on_sale %>
   <%= f.input :sale_price %>
   <%= f.association :category, :collection => Category.all(:order => 'name'), :include_blank => false, :label => 'Select Category'  %>   
   <%= f.button :submit, :class => 'btn btn-primary' %>


<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table class="table table-condensed table-bordered table-striped">
  <tr>
    <th>Name</th>    
    <th>Qty</th>
    <th>Price</th>
    <th>On sale</th>
    <th>Sale price</th>
    <th>Category</th>    
    <th>Action</th> 

  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= link_to product.name , admin_product_path(product) %></td>
    <td><%= product.qty %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= product.on_sale %></td>
    <td><%= number_to_currency(product.sale_price )%></td>
    <td><%= product.category.name %></td>
    <td>
        <%= link_to 'Show', admin_product_path(product), :class =>"btn btn-mini btn-info" %>
        <%= link_to 'Edit', edit_admin_product_path(product), :class =>"btn btn-mini" %>
        <%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-mini btn-danger" %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path, :class => 'btn btn-primary'%>

<%= paginate @products %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Qty:</b>
  <%= @product.qty %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>On sale:</b>
  <%= @product.on_sale %>
</p>

<p>
  <b>Sale price:</b>
  <%= @product.sale_price %>
</p>

<p>
    <%= image_tag @product.picture.url if @product.picture %>
</p>



<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>