config/routes.rb
MyeCommerce::Application.routes.draw do
	

    #common
    match '/admin',   to: 'admin/products#index'  
 
    (StaticPagesController.action_methods - ApplicationController.action_methods).each do |am|
      match "/#{am}" => "static_pages##{am}"
    end

    root to: 'static_pages#home'

    #back-end
    namespace "admin" do
		  resources :products, :categories
	  end

    #front-end Store 

    resources :items, :only => [:create, :destroy]
    resources :carts, only: [:show, :destroy]
    
    resources :products, :only => [:show]
    resources :categories, :only => [:show]

  	devise_for :users
    
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin? 
         can :manage, :all         
       #can :manage, :all    # fix this   
       #  can :show_category, Product
       #  can :show_product, Category
       #  cannot [:index, :show, :new, :edit, :create, :update, :destroy], [Product, Category]           
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :user_id
  has_many 	:items
  has_many	:products, :through => :items


  def add_item(product)  
    item = Item.find_or_initialize_by_cart_id_and_product_id(self.id, product.id)
    item.qty = (item.qty || 0) + 1
    item.save   
  end

  def remove_item(product)
    item = Item.find_by_cart_id_and_product_id( self.id, product.id)
    item.destroy
  end

  def cart_count    
    items.to_a.sum(&:qty) 
  end

  def cart_price
    items.to_a.sum(&:total_price)    
  end
end

app/models/cart_observer.rb
class CartObserver < ActiveRecord::Observer

	def after_update(cart)
		    
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :color, :name
  has_many :products

  validates_presence_of :color, :name
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :qty
  belongs_to	:cart
  belongs_to	:product


  def total_price
  	self.product.price * self.qty  	
  end
end

app/models/item_observer.rb
class ItemObserver < ActiveRecord::Observer

	def after_update(item)
    UserMailer.product_added(User.find(item.cart.user_id), item.product).deliver
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :on_sale, :price, :qty, :sale_price, :category_id, :picture
  
  belongs_to :category
  has_many 	:items
  has_many	:carts, :through => :items

  if Rails.env.production?
   has_attached_file :picture, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :storage => :s3, :s3_credentials => S3_CREDENTIALS
 else
   has_attached_file :picture, :styles => { :medium => "200x200>", :thumb => "100x100>" }
 end

 

 validates_presence_of :description, :name, :price, :qty
 validates_uniqueness_of :name
 validates_numericality_of :price, :qty, greater_than_or_equal_to: 0


 validates_attachment :picture,
 content_type: { content_type: /^image\/.?(gif|png|jpg|jpeg)$/i },
 size: { in: 1..500.kilobytes }
 
 scope :in_stock, where("qty > ?", 0)

  #searchable do
    #text :name, :description
  #end

  def total_price
    on_sale ? sale_price : price
  end

  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['name LIKE ? OR description LIKE ?', search_condition, search_condition])
  end



end

app/models/product_observer.rb
class ProductObserver < ActiveRecord::Observer
	def after_update(product)
    
    if product.price_changed?
    		Item.find_all_by_product_id(product.id).each do |item|
        UserMailer.price_changed(User.find(item.cart.user_id), item.product).deliver        
      end 
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :birthday, :country, :avatar, :admin

  
  if Rails.env.production?
    has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "80x80>" }, :storage => :s3, :s3_credentials => S3_CREDENTIALS  
  else
    has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "80x80>" }
  end

  has_one :cart, dependent: :destroy

  # VALIDATIONS
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  validates :email, :presence => true, length: { maximum: 255 }, :format => { with: VALID_EMAIL_REGEX },
  :uniqueness => { case_sensitive: false }

  before_save { |user| user.email = email.downcase }


  validates_attachment :avatar,
  content_type: { content_type: /^image\/.?(gif|png|jpg|jpeg)$/i },
  size: { in: 1..500.kilobytes }
  
  validates_presence_of :password, :password_confirmation, :first_name, :last_name, :country
  validates_uniqueness_of :email


  def my_cart
    @cart ||= Cart.find_or_create_by_user_id(self.id)
  end
  

  def full_name
    [first_name, last_name].join(' ').strip
  end
  
end

app/controllers/admin_controller.rb
class AdminController <ApplicationController
	layout "application"
	before_filter :authenticate_user!, :authenticate_admin

	def authenticate_admin
		redirect_to root_path, alert: "Must be admin to acces this page" unless current_user.admin?
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  respond_to :html, :json, :js   
  layout "store_layout"
  before_filter :authenticate_user!
  def show
  	@cart=current_user.my_cart
  	@items = @cart.items

  end

  def destroy
  	
    @cart = Cart.find(params[:id])    
  	@cart.items.destroy_all
  	respond_with(@cart)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :html, :json, :js

   layout "store_layout"


  def show
    @category = Category.find(params[:id])
    @products = @category.products.in_stock

  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def create
  		cart=current_user.my_cart
  		product = Product.find(params[:id])
  		cart.add_item(product)
    	redirect_to cart_path(cart)    	
  end

  def destroy

      item = Item.find(params[:id])
  		cart=item.cart
  		product = item.product
  		cart.remove_item(product)
      cart.save
    	redirect_to cart_path(cart)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	layout "store_layout"

	respond_to :html, :json, :js
	before_filter :authenticate_user!


	def show
		@product = Product.find(params[:id])
		respond_with(@product)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def print_categories

		raw(
			Category.all.collect do |category|                    
				content_tag :li do
				 content_tag :div do 
					link_to category.name, category_path(category),:style => "color: #{category.color}"       	
					end
				end
			end.join
			)
	end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper


end

app/views/layouts/_footer.html.erb
<footer>
	<center>
		<small>Footer back-end</small>
	</center>
</footer>

app/views/layouts/_footer_store.html.erb
<div id="footer">
		<div class="contact">
			<h2>Contact Information</h2>
			<ul>
				<li>My eCommerce</li>
				<li>
					Phone: <span>3017174143</span>
				</li>
				<li>
					Email: <a href="mailto:edyhack@gmail.com">edyhack@gmail.com</a> 
				</li>
				<li>
					Twitter: <a href="http://www.twitter.com/edymerchk">edymerchk</a>
				</li>
				<li>
					Facebook: <a href="http://facebook.com/edymerchj">Edymerchk</a>
				</li>
			</ul>
		</div>	
		<div class="payment-methods">
			<h2>Payment Methods</h2>
			<ul>
				<li><img src="http://cdn.shopify.com/s/files/1/0108/3862/t/4/assets/icon-paypal.png?0" alt="Paypal"></li>
				<li><img src="http://cdn.shopify.com/s/files/1/0108/3862/t/4/assets/icon-visa.png?0" alt="Paypal"></li>
				<li><img src="http://cdn.shopify.com/s/files/1/0108/3862/t/4/assets/icon-amex.png?0" alt="Paypal"></li>
				<li><img src="http://cdn.shopify.com/s/files/1/0108/3862/t/4/assets/icon-mastercard.png?0" alt="Paypal"></li>
				<li><img src="http://cdn.shopify.com/s/files/1/0108/3862/t/4/assets/icon-discover.png?0" alt="Paypal"></li>
			</ul>
		</div>
		<div class="useful-links">
			<h2>Useful Links</h2>
			<ul>				
				<li><a id="search" href="/search">Search</a></li>				
				<li><%= link_to "About Us", about_path %></a></li>   
					
			</ul>
		</div>
		<div>
			<h2>Store Description</h2>
			<p>This project is about to write very basic eCommerce site and get used various parts of a rails stack.</p>
		</div>
		<div class="sub-floor">
			<p class="copyright">© My eCommerce by Edymerchk, All Rights Reserved...</p>			
		</div>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <%= link_to "MyEcommerce", root_path, :class => 'brand'  %>
        <div class="nav-collapse">
          <ul class="nav">
                <li><%= link_to "Products", admin_products_path %></li>
                <li><%= link_to "Categories", admin_categories_path %></li>
           </ul>
        </div>
        <% if user_signed_in? %>
          <div class="btn-group pull-right">
            
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> Admin
              <span class="caret"></span>

            </a>
            <ul class="dropdown-menu">
              
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/_header_store.html.erb
<div id="header">
  <div id="page-title">
    <h1>
      <a href="/">
        <strong>My eCommerce</strong>
      </a>
    </h1>
    <h3><em>Your Staunch Store</em></h3>
  </div>
  <ol id="main-nav">
    <li class="with-dropdown"><a href="#" title="">Catalog</a>
      <ul>
       <%= print_categories %>
     </ul>
   </li>
   <% if current_user %>
   <li><%= link_to "My Cart", cart_path(current_user.my_cart)%></a></li>      
   <% end %>
   <li><%= link_to "About Us", about_path %></a></li>           
   <% if can? :manage, :all %>
   <li><%= link_to "Admin", admin_path %></a></li>
   <% end %>


 </ol>    
 <p id="utility">

  <span class="customer">
    <% if user_signed_in? %>

    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>

    <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
    <% end %>      
  </span>    
  <% if current_user %>
  <%= link_to cart_path(current_or_guest_user.my_cart), :class => "cart" do %> 
  <span><i><em>items</em> <%=current_or_guest_user.my_cart.cart_count%></i> <b><%=number_to_currency(current_or_guest_user.my_cart.cart_price)%></b></span>
  <%end%>
  <%= image_tag current_user.avatar.url(:thumb), class: "avatar" %>
  <%end%>      
</p>

  <%= form_tag search_path do %>
 <p>
  <%= text_field_tag :search, params[:search], :class => "searchtext-2" %>
  <%= submit_tag "Search", type: "image", id: "search_btn",  src: "http://cdn.shopify.com/s/files/1/0108/3862/t/4/assets/c7-search-btn.gif" %>
  
</p>
<% end %>


</div>

app/views/layouts/_msgs.html.erb
    <div class="row">
          <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name %>">
              <a class="close" data-dismiss="alert">×</a>
              <%= msg %>
            </div>
          <% end %>        
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MyeCommerce-Administration</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", controller_name %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/msgs' %>
    


    <div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
    </div>
    <div class="span8">
      <%= yield %>
    </div>
  </div>
</div>

  <div>
    <% if user_signed_in? %>
      <%= image_tag current_user.avatar.url(:thumb) if current_user.avatar %>
      Logged in as <strong><%= current_user.email %></strong>.      
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>    
  
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/store_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<%= stylesheet_link_tag "print",  :media => "print" %>
	<%= stylesheet_link_tag "base",  :media => "all" %>
	<%= stylesheet_link_tag "c7-screen",  :media => "all" %>
	<%= stylesheet_link_tag "customer",  :media => "all" %>
	<%= stylesheet_link_tag "bootstrap-datepicker",  :media => "all" %>

		
	<%= javascript_include_tag "application", controller_name %>
</head>
<body>	
	
	<div id="wrapper">
		<%= render 'layouts/header_store' %>
		<%= render 'layouts/msgs' %>
		<%= yield %>
	</div>
	<div id="footer-wrapper">	
  		<%= render 'layouts/footer_store' %>
  	</div>

</body>
</html>